<?php

function sitedir_migrate_body_sitedir_query() {
  return 'Node Bodies';
}

function sitedir_migrate_body_sitedir_update() {
  watchdog('Sitedir Migrate', 'Running the Node Body migration');
  $args = func_get_args();
  $from = $args[0];
  $to = $args[1];
  db_query("UPDATE {field_data_body} SET body_value = replace(body_value,'%s','%s')", array($from, $to));
  db_query("UPDATE {field_revision_body} SET body_value = replace(body_value,'%s','%s')", array($from, $to));
}
